name: actions_on_main_branch
on: [pull_request]

jobs:
  job1:
    name: enforce_merge
    runs-on: ubuntu-latest
#    env:
#      NAME_ADMIN: adminA
    steps:
      - name: step 1
        run: |
          echo "Head Ref: $GITHUB_HEAD_REF"
          echo "Base Ref: $GITHUB_BASE_REF"
#       - name: check branch
#         if: ${{ $GITHUB_HEAD_REF == "develop" && $GITHUB_BASE_REF" == "master" }}
#         run: echo "Able to merge"
#       - name: st2
#         if: ! ${{ $GITHUB_HEAD_REF == "develop" && $GITHUB_BASE_REF" == "master" }}
#         run: exit 2
      - name: Branch checks
        run: |
          if [[ ! ( \
            "$GITHUB_HEAD_REF" == "development" \
            && "$GITHUB_BASE_REF" == "master"
          ) ]]; then
            exit 2
          fi
