name: actions_on_main_branch
on: [pull_request]

jobs:
  job1:
    name: enforce_merge
    runs-on: ubuntu-latest
#    env:
#      NAME_ADMIN: adminA
    steps:
      - name: step 1
        run: |
          echo "Head Ref: $GITHUB_HEAD_REF"
          echo "Base Ref: $GITHUB_BASE_REF"
      - name: Branch checks
        run: |
          if [[ ! ( \
            "$GITHUB_HEAD_REF" == "develop" \
            && "$GITHUB_BASE_REF" == "main"
          ) ]]; then
            echo "Cannot merge $GITHUB_HEAD_REF branch to $GITHUB_BASE_REF branch"
            exit 2
          fi
